remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
title: Samira Korani
logo: assets/img/logo.png
description: &description "Computational Linguistics\n Natural Language Processing\n Knowledge Graph\n Machine Learning\n Email:Samira.korani@gmail.com\n &nbsp; &nbsp;
s.korani1@nuigalway.ie"
show_downloads: False
Google Analytics: 




