remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
title: Samira Korani
show_downloads: False
google_analytics:
theme: jekyll-theme-minimal
description: >
   title: Computational Linguistics
   title: Natural Language Processing 
   title: Machine Learning



