remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
title: Samira Korani
logo: assets/img/logo.png
description: >
  Computational Linguistics,
  Natural Language Processing,
  Machine Learning
show_downloads: False
google_analytics: 

email:
  id: 'your.name@yoursite.com'
  href: 'mailto:'
  title: 'Email'
  fa-icon: 'fa-envelope-square'

twitter:
  id: 'your-twitter-name'
  href: 'https://www.twitter.com/'
  title: 'Twitter'
  fa-icon: 'fa-twitter-square'

github:
  id: 'your-github-name'
  href: 'https://github.com/'
  title: 'GitHub'
  fa-icon: 'fa-github-square'

